# site settings


title: Gilberto
subtitle: Robles
email: giroblesilva@gmail.com
description: Documenting my learning experiences!
#: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
#url: # the base hostname & protocol for your site
author: Gilberto Robles
city: San Diego
state: CA
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/gilbertorobles24
  LinkedIn: https://www.linkedin.com/in/gilbertorobles

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
